name: CI Build
on:
  push:
    branches:
      - main-mac
    pull_requests:
      - main-mac
jobs:
  build-and-deploy:
    name: build python_tool
    runs-on: x86_64_monterey
  steps:
    - uses: actions/checkout@v4
    - name: Installhomebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install from requirements.txt
      run: pip install -r requirements.txt

