name: CI Build
on:
  push:
    branches:
      - main-mac
    pull_requests:
      - main-mac
jobs:
  build-and-deploy:
    name: build python_tool
    runs-on: x86_64_catalina
  steps:
    - name: install from requirements.txt
      run: pip install -r requirements.txt

