name: CI Build(macos)


on:
  workflow_run:
    workflows: [ Staging, Lab ]
    types:
      - completed
  push:




jobs:
  build-and-deploy:
    name : build pyinstaller
    runs-on: macos-13
    steps:
    - name: check
      uses: actions/checkout@v4
    - name: install from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build python_tool for macos
      run: |
        cd /Users/runner/work/python_tool/python_tool
        bash build.sh
        cd /Users/runner/work/python_tool/
        mv /Users/runner/work/python_tool/python_tool
    - name: publish python-tool.zip
      run: |
        
        sudo rm -rf python_tool
        cd /Users/runner/work/python_tool/python_tool/python_tool/dist/python_tool.app
        zip -pr python_tool.zip ./*
