name: CI Build
on:
  push:
    branches:
      - main-mac
    pull_requests:
      - main-mac
jobs:
  build:
    runs-on: x86_64_catalina
  steps:
    - name: install from requirements.txt
      run: pip install -r requirements.txt

