name: CI Build(macos)


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  check_run:
    types: [ rerequested, completed ]



jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
    - name: check
      uses: actions/python_tool@main-mac
    - name: install from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

